package com.kairo.reader.ui.settings

import com.kairo.reader.R

internal val rsvpSearchEntries = listOf(
    SettingsSearchEntry(
        id = "rsvp.rsvp_reading_speed_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_reading_speed_title,
        descriptionRes = R.string.rsvp_reading_speed_details_subtitle,
        sectionRes = R.string.rsvp_quick_tune_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_min_word_time_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_min_word_time_title,
        descriptionRes = R.string.rsvp_min_word_time_subtitle,
        sectionRes = R.string.rsvp_readability_floors_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_long_word_min_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_long_word_min_title,
        descriptionRes = R.string.rsvp_long_word_min_subtitle,
        sectionRes = R.string.rsvp_readability_floors_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_sentence_end_pause_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_sentence_end_pause_title,
        descriptionRes = R.string.rsvp_sentence_end_pause_subtitle,
        sectionRes = R.string.rsvp_readability_floors_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_adaptive_pacing_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_adaptive_pacing_title,
        descriptionRes = R.string.rsvp_adaptive_pacing_subtitle,
        sectionRes = R.string.rsvp_readability_floors_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_phrase_chunking_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_phrase_chunking_title,
        descriptionRes = R.string.rsvp_phrase_chunking_subtitle,
        sectionRes = R.string.rsvp_comprehension_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_phrase_chunk_size_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_phrase_chunk_size_title,
        descriptionRes = R.string.rsvp_phrase_chunk_size_subtitle,
        sectionRes = R.string.rsvp_comprehension_title,
        requiresRes = R.string.rsvp_phrase_chunking_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_regression_pacing_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_regression_pacing_title,
        descriptionRes = R.string.rsvp_regression_pacing_subtitle,
        sectionRes = R.string.rsvp_comprehension_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.reader_font_size_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.reader_font_size_title,
        descriptionRes = R.string.settings_search_font_size_description,
        sectionRes = R.string.rsvp_display_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.reader_text_brightness_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.reader_text_brightness_title,
        descriptionRes = R.string.rsvp_text_brightness_subtitle,
        sectionRes = R.string.rsvp_display_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_orp_guide_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_orp_guide_title,
        descriptionRes = R.string.rsvp_orp_guide_subtitle,
        sectionRes = R.string.rsvp_display_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_orp_highlight_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_orp_highlight_title,
        descriptionRes = R.string.rsvp_orp_highlight_subtitle,
        sectionRes = R.string.rsvp_display_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_orp_guide_brightness_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_orp_guide_brightness_title,
        descriptionRes = R.string.rsvp_orp_guide_brightness_subtitle,
        sectionRes = R.string.rsvp_display_title,
        requiresRes = R.string.rsvp_orp_guide_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_orp_guide_thickness_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_orp_guide_thickness_title,
        descriptionRes = R.string.rsvp_orp_guide_thickness_subtitle,
        sectionRes = R.string.rsvp_display_title,
        requiresRes = R.string.rsvp_orp_guide_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_unlock_extreme_speeds_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_unlock_extreme_speeds_title,
        descriptionRes = R.string.rsvp_unlock_extreme_speeds_subtitle_long,
        sectionRes = R.string.rsvp_speed_limits_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_long_word_threshold_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_long_word_threshold_title,
        descriptionRes = R.string.settings_search_long_threshold_description,
        sectionRes = R.string.rsvp_readability_floors_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_split_word_pause_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_split_word_pause_title,
        descriptionRes = R.string.rsvp_split_word_pause_subtitle,
        sectionRes = R.string.rsvp_readability_floors_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_syllable_boost_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_syllable_boost_title,
        descriptionRes = R.string.settings_search_syllables_description,
        sectionRes = R.string.rsvp_difficulty_model_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_rarity_boost_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_rarity_boost_title,
        descriptionRes = R.string.settings_search_rarity_description,
        sectionRes = R.string.rsvp_difficulty_model_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_complexity_strength_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_complexity_strength_title,
        descriptionRes = R.string.settings_search_complexity_description,
        sectionRes = R.string.rsvp_difficulty_model_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_breathing_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_breathing_title,
        descriptionRes = R.string.rsvp_punctuation_breathing_subtitle,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_comma",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_comma,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_period",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_period,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_dash",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_dash,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_semicolon",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_semicolon,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_colon",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_colon,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_parentheses",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_parentheses,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_quotes",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_quotes,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_paragraph",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_paragraph,
        descriptionRes = R.string.settings_search_punctuation_description,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_paragraph_strength_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_paragraph_strength_title,
        descriptionRes = R.string.rsvp_punctuation_paragraph_strength_subtitle,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_page_break_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_page_break_title,
        descriptionRes = R.string.rsvp_punctuation_page_break_subtitle,
        sectionRes = R.string.rsvp_punctuation_pauses_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_scale_exponent_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_scale_exponent_title,
        descriptionRes = R.string.rsvp_scale_exponent_subtitle,
        sectionRes = R.string.rsvp_pause_scaling_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_minimum_scale_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_minimum_scale_title,
        descriptionRes = R.string.rsvp_minimum_scale_subtitle,
        sectionRes = R.string.rsvp_pause_scaling_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_parentheticals_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_parentheticals_title,
        descriptionRes = R.string.settings_search_parentheticals_description,
        sectionRes = R.string.rsvp_context_shaping_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_dialogue_pace_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_dialogue_pace_title,
        descriptionRes = R.string.settings_search_dialogue_description,
        sectionRes = R.string.rsvp_context_shaping_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_dialogue_punctuation_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_dialogue_punctuation_title,
        descriptionRes = R.string.rsvp_dialogue_punctuation_subtitle,
        sectionRes = R.string.rsvp_context_shaping_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_parenthetical_aside_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_parenthetical_aside_title,
        descriptionRes = R.string.rsvp_parenthetical_aside_subtitle,
        sectionRes = R.string.rsvp_context_shaping_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_parenthetical_aside_pace_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_parenthetical_aside_pace_title,
        descriptionRes = R.string.rsvp_parenthetical_aside_pace_subtitle,
        sectionRes = R.string.rsvp_context_shaping_title,
        advanced = true,
        requiresRes = R.string.rsvp_parenthetical_aside_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_difficulty_boost_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_difficulty_boost_title,
        descriptionRes = R.string.rsvp_difficulty_boost_subtitle,
        sectionRes = R.string.rsvp_adaptive_pacing_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_complex_word_boost_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_complex_word_boost_title,
        descriptionRes = R.string.rsvp_complex_word_boost_subtitle,
        sectionRes = R.string.rsvp_adaptive_pacing_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_complex_word_threshold_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_complex_word_threshold_title,
        descriptionRes = R.string.rsvp_complex_word_threshold_subtitle,
        sectionRes = R.string.rsvp_adaptive_pacing_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_stability_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_stability_title,
        descriptionRes = R.string.rsvp_stability_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_focal_stress_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_focal_stress_title,
        descriptionRes = R.string.rsvp_focal_stress_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_focal_support_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_focal_support_title,
        descriptionRes = R.string.rsvp_focal_support_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
        requiresRes = R.string.rsvp_focal_stress_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_anticipatory_landing_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_anticipatory_landing_title,
        descriptionRes = R.string.rsvp_anticipatory_landing_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_anticipatory_landing_strength_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_anticipatory_landing_strength_title,
        descriptionRes = R.string.rsvp_anticipatory_landing_strength_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
        requiresRes = R.string.rsvp_anticipatory_landing_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_clause_pacing_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_clause_pacing_title,
        descriptionRes = R.string.rsvp_clause_pacing_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_clause_strength_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_clause_strength_title,
        descriptionRes = R.string.rsvp_clause_strength_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
        requiresRes = R.string.rsvp_clause_pacing_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_prosody_pacing_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_prosody_pacing_title,
        descriptionRes = R.string.rsvp_prosody_pacing_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_prosody_strength_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_prosody_strength_title,
        descriptionRes = R.string.rsvp_prosody_strength_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
        requiresRes = R.string.rsvp_prosody_pacing_title,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_punctuation_landing_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_punctuation_landing_title,
        descriptionRes = R.string.rsvp_punctuation_landing_subtitle,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_vertical_position_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_vertical_position_title,
        descriptionRes = R.string.settings_search_vertical_description,
        sectionRes = R.string.rsvp_display_details_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_left_bias_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_left_bias_title,
        descriptionRes = R.string.settings_search_horizontal_description,
        sectionRes = R.string.rsvp_display_details_title,
        advanced = true,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_profile_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_profile_title,
        descriptionRes = R.string.settings_search_profiles_description,
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_font_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_font_title,
        descriptionRes = R.string.settings_search_font_description,
        sectionRes = R.string.rsvp_display_details_title,
        advanced = true,
        aliases = listOf(R.string.rsvp_font_family_inter, R.string.rsvp_font_family_roboto),
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_weight_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_weight_title,
        descriptionRes = R.string.settings_search_weight_description,
        sectionRes = R.string.rsvp_display_details_title,
        advanced = true,
        aliases = listOf(R.string.rsvp_font_weight_light, R.string.rsvp_font_weight_normal, R.string.rsvp_font_weight_medium),
    ),
    SettingsSearchEntry(
        id = "rsvp.blink_mode_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.blink_mode_title,
        descriptionRes = R.string.settings_search_blink_description,
        sectionRes = R.string.rsvp_rhythm_title,
        advanced = true,
        aliases = listOf(R.string.blink_mode_off, R.string.blink_mode_subtle, R.string.blink_mode_adaptive),
    ),
    SettingsSearchEntry(
        id = "rsvp.rsvp_context_assist_title",
        page = SettingsSearchPage.RSVP,
        titleRes = R.string.rsvp_context_assist_title,
        descriptionRes = R.string.settings_search_context_description,
        sectionRes = R.string.rsvp_comprehension_title,
        aliases = listOf(
            R.string.rsvp_context_assist_off,
            R.string.rsvp_context_assist_previous,
            R.string.rsvp_context_assist_clause,
            R.string.rsvp_context_assist_ticker
        ),
    ),
)
