package com.kairo.reader.ui.rsvp

import androidx.compose.ui.unit.dp
import com.kairo.reader.core.model.DEFAULT_RSVP_FONT_SIZE_SP
import com.kairo.reader.core.model.PAIRED_OPENING_PUNCTUATION_CHARS
import com.kairo.reader.core.model.RsvpFontFamily
import com.kairo.reader.core.model.RsvpFontWeight
import com.kairo.reader.core.rsvp.RsvpSpeedControl

const val DEFAULT_FONT_SIZE_SP = DEFAULT_RSVP_FONT_SIZE_SP
val DEFAULT_FONT_FAMILY = RsvpFontFamily.INTER
val DEFAULT_FONT_WEIGHT = RsvpFontWeight.LIGHT
const val DEFAULT_TEXT_BRIGHTNESS = 0.88f
const val DEFAULT_VERTICAL_BIAS = -0.15f
const val DEFAULT_HORIZONTAL_BIAS = 0f

const val SAFE_MIN_TEMPO_MS_PER_WORD = RsvpSpeedControl.SAFE_MIN_TEMPO_MS_PER_WORD
const val EXTREME_MIN_TEMPO_MS_PER_WORD = RsvpSpeedControl.EXTREME_MIN_TEMPO_MS_PER_WORD
const val MAX_TEMPO_MS_PER_WORD = RsvpSpeedControl.MAX_TEMPO_MS_PER_WORD
const val DEFAULT_TEMPO_SCALE = 1.0
const val TEMPO_SCALE_MIN = 0.1
const val TEMPO_SCALE_MAX = 4.0
const val MIN_FRAME_DELAY_MS = 16L
const val POSITION_SAVE_INTERVAL_MS = 750L
const val TEMPO_STEP_MS = 5L
const val SPEED_STEP_PERCENT = 2f
const val TEMPO_SWIPE_THRESHOLD_PX = 30f
const val DRAG_AXIS_LOCK_THRESHOLD_PX = 12f
const val SWEEP_SWIPE_THRESHOLD_PX = 30f
const val SWEEP_FRAME_STEP = 1
const val REGRESSION_PACE_STEP = 0.06f
const val REGRESSION_PACE_MAX_SCALE = 1.18f
const val REGRESSION_RECOVERY_START_PHRASES = 1
const val REGRESSION_RECOVERY_STEP = 0.02f
const val REPLAY_PHRASE_MAX_WORDS = 12
const val POSITIONING_BIAS_PER_PX = 0.0015f

// Positioning-mode adjustment grid: alignment lines every POSITIONING_GRID_SPACING_BIAS on both
// axes. The snap-strength preference (0..1) scales the capture radius around each line up to
// half the spacing — at 1.0 the position quantizes fully to the grid, at 0 it is free-form.
const val POSITIONING_GRID_SPACING_BIAS = 0.1f
const val DEFAULT_POSITIONING_GRID_SNAP = 0.5f
const val POSITIONING_GRID_LINE_NONE = Int.MIN_VALUE

const val LOADING_TEXT_ALPHA = 0.6f
const val PROGRESS_PRIMARY_ALPHA = 0.7f
const val PROGRESS_TRACK_ALPHA = 0.18f
const val TOP_BAR_ICON_ALPHA = 0.54f
const val TOP_BAR_BUTTON_BACKGROUND_ALPHA = 0.18f
const val TOP_BAR_BUTTON_BORDER_ALPHA = 0.08f
const val INDICATOR_BACKGROUND_ALPHA = 0.9f
const val QUICK_SETTINGS_BACKGROUND_ALPHA = 0.97f
const val QUICK_SETTINGS_BORDER_ALPHA = 0.18f
const val QUICK_SETTINGS_HANDLE_ALPHA = 0.42f
const val CONTROLS_BACKGROUND_ALPHA = 0.72f
const val CONTROLS_BORDER_ALPHA = 0.10f
const val CONTROLS_PILL_BACKGROUND_ALPHA = 0.34f
const val CONTROLS_PILL_LABEL_ALPHA = 0.48f
const val CONTROLS_PILL_VALUE_ALPHA = 0.78f
const val POSITIONING_LINE_ALPHA = 0.10f
const val POSITIONING_GRID_LINE_ALPHA = 0.07f
const val POSITIONING_GRID_CENTER_LINE_ALPHA = 0.16f
const val PROGRESS_TEXT_ALPHA = 0.6f
const val RESUME_TEXT_ALPHA = 0.4f
const val PAUSE_PREVIEW_TEXT_ALPHA = 0.74f
const val PAUSE_PREVIEW_FOCUS_ALPHA = 0.96f
const val PAUSE_PREVIEW_SURFACE_ALPHA = 0.22f
const val PAUSE_PREVIEW_BORDER_ALPHA = 0.12f
const val PAUSE_PREVIEW_HIGHLIGHT_BACKGROUND_ALPHA = 0.16f
const val PAUSE_PREVIEW_FONT_SCALE = 0.48f
const val PAUSE_PREVIEW_COMPACT_FONT_SCALE = 0.42f
const val PAUSE_PREVIEW_FOCUS_FONT_SCALE = 0.72f
const val PAUSE_PREVIEW_COMPACT_FOCUS_FONT_SCALE = 0.58f
const val MIN_PAUSE_PREVIEW_FONT_SIZE_SP = 16f
const val MAX_PAUSE_PREVIEW_FONT_SIZE_SP = 22f
const val MAX_PAUSE_PREVIEW_COMPACT_FONT_SIZE_SP = 19f
const val MIN_PAUSE_PREVIEW_FOCUS_SIZE_SP = 22f
const val MAX_PAUSE_PREVIEW_FOCUS_SIZE_SP = 34f
const val MAX_PAUSE_PREVIEW_COMPACT_FOCUS_SIZE_SP = 27f
const val PAUSE_PREVIEW_LINE_HEIGHT_MULTIPLIER = 1.42f
const val PARAGRAPH_PREVIEW_WINDOW_WORDS = 82
const val PAUSE_PREVIEW_COMPACT_WINDOW_WORDS = 42
const val PAUSE_PREVIEW_HIGHLIGHT_FRACTION = 0.38f
const val PAUSE_PREVIEW_LINES = 4
const val PAUSE_PREVIEW_COMPACT_LINES = 3

const val TEXT_BRIGHTNESS_MIN = 0.55f
const val TEXT_BRIGHTNESS_MAX = 1.0f
const val PIVOT_LINE_ALPHA_BASE = 0.06f
const val PIVOT_LINE_ALPHA_MIN = 0f
const val PIVOT_LINE_ALPHA_MAX = 1f

const val VERTICAL_BIAS_MIN = -0.7f
const val VERTICAL_BIAS_MAX = 0.7f
const val HORIZONTAL_BIAS_MIN = -0.6f
const val HORIZONTAL_BIAS_MAX = 0.6f

const val MIN_FONT_SIZE_SP = 16f
const val MAX_FONT_SIZE_SP = 80f

const val CONTROLS_HIDE_DELAY_MS = 3000L
const val TEMPO_INDICATOR_HIDE_DELAY_MS = 1500L
const val FONT_SIZE_INDICATOR_HIDE_DELAY_MS = 1500L

const val PERCENT_SCALE = 100f
const val MS_PER_MINUTE = 60_000.0
const val MIN_WORD_COUNT = 1
const val MIN_TOTAL_MS = 1L

const val DEFAULT_PIVOT_INDEX = 0
const val INVALID_INDEX = -1
const val ORP_LOCK_PIVOT_WORDS = 1
const val ORP_LETTER_SPACING_SP = 0.5f
const val ORP_GUIDE_BRIGHTNESS_MIN = 0.25f
const val ORP_GUIDE_BRIGHTNESS_MAX = 2.0f
const val ORP_GUIDE_THICKNESS_MIN = 0.5f
const val ORP_GUIDE_THICKNESS_MAX = 3.0f
const val ORP_BIAS_FRACTION_MIN = 0.05f
const val ORP_BIAS_FRACTION_MAX = 0.95f
const val ORP_EDGE_FRACTION_MIN = 0.05f
const val ORP_EDGE_FRACTION_MAX = 0.45f
const val ORP_CENTER_FRACTION = 0.5f
const val ORP_TRANSFORM_ORIGIN_X = 0f
const val ORP_TRANSFORM_ORIGIN_Y = 0.5f
const val ORP_TEXT_LINE_HEIGHT_MULTIPLIER = 1.18f
const val MIN_ORP_WIDTH_PX = 1f
const val ORP_MIN_AUTO_FIT_SCALE = 0.72f
const val ORP_ELLIPSIS = '\u2026'
const val ORP_DISPLAY_CACHE_SIZE = 96
const val ORP_DISPLAY_CACHE_LOAD_FACTOR = 0.75f

const val ZERO_FLOAT = 0f
const val ONE_FLOAT = 1f
const val CENTER_BIAS = 0f
const val BIAS_SCALE_FACTOR = 2f

val PROGRESS_HEIGHT = 4.dp
val PROGRESS_HORIZONTAL_PADDING = 16.dp
val PROGRESS_BOTTOM_PADDING = 10.dp
val PROGRESS_CORNER_RADIUS = 8.dp
val TOP_BAR_PADDING = 16.dp
val TOP_BAR_SPACING = 12.dp
val TOP_BAR_BUTTON_SIZE = 40.dp
val TOP_BAR_ICON_SIZE = 22.dp
val TEMPO_INDICATOR_TOP_PADDING = 60.dp
val FONT_SIZE_INDICATOR_TOP_PADDING = 112.dp
val SCRUB_INDICATOR_TOP_PADDING = 52.dp

// Word-aware indicator placement: estimated pill height plus the gap kept between an indicator
// pill and the focus-word band when the pill has to flip below it.
val INDICATOR_APPROX_HEIGHT = 40.dp
val INDICATOR_WORD_CLEARANCE = 16.dp
val INDICATOR_CORNER_RADIUS = 8.dp
val INDICATOR_PADDING_HORIZONTAL = 16.dp
val INDICATOR_PADDING_VERTICAL = 8.dp
val POSITIONING_INDICATOR_PADDING_HORIZONTAL = 14.dp
val POSITIONING_INDICATOR_PADDING_VERTICAL = 8.dp
val QUICK_SETTINGS_CORNER = 8.dp
val QUICK_SETTINGS_MAX_WIDTH = 640.dp
val QUICK_SETTINGS_OUTER_PADDING = 8.dp
val QUICK_SETTINGS_HANDLE_WIDTH = 44.dp
val QUICK_SETTINGS_HANDLE_HEIGHT = 4.dp
val QUICK_SETTINGS_HANDLE_BOTTOM_PADDING = 2.dp
val QUICK_SETTINGS_HORIZONTAL_PADDING = 16.dp
val QUICK_SETTINGS_VERTICAL_PADDING = 14.dp
val QUICK_SETTINGS_SPACING = 12.dp
const val QUICK_SETTINGS_HEIGHT_FRACTION = 0.85f
val POSITION_GUIDE_HEIGHT = 1.dp
const val ORP_COLLISION_TEXT_HEIGHT_MULTIPLIER = 1.15f
val CONTROLS_ORP_CLEARANCE = 18.dp
val PAUSE_PREVIEW_CORNER_RADIUS = 8.dp
val PAUSE_PREVIEW_PADDING_HORIZONTAL = 18.dp
val PAUSE_PREVIEW_PADDING_VERTICAL = 14.dp
val PAUSE_PREVIEW_COMPACT_PADDING_HORIZONTAL = 14.dp
val PAUSE_PREVIEW_COMPACT_PADDING_VERTICAL = 10.dp
val PAUSE_PREVIEW_FOCUS_SPACING = 10.dp
val PAUSE_PREVIEW_COMPACT_FOCUS_MIN_WIDTH = 96.dp
val PAUSE_PREVIEW_COMPACT_FOCUS_MAX_WIDTH = 156.dp
val PAUSE_PREVIEW_BOTTOM_SPACING = 14.dp
val PAUSE_PREVIEW_COMPACT_BOTTOM_SPACING = 8.dp

val CONTROLS_PADDING = 18.dp
val CONTROLS_SPACER = 10.dp
val CONTROLS_HINT_SPACER = 4.dp
val CONTROLS_ROW_SPACING = 28.dp
val CONTROLS_MAX_WIDTH = 640.dp
const val CONTROLS_WIDTH_FRACTION = 0.92f
val CONTROLS_OUTER_PADDING = 12.dp
val CONTROLS_CORNER_RADIUS = 8.dp
val CONTROLS_PROGRESS_HEIGHT = 4.dp
val CONTROLS_PROGRESS_CORNER_RADIUS = 8.dp
val CONTROLS_INFO_SPACING = 8.dp
val CONTROLS_INFO_PILL_PADDING_HORIZONTAL = 12.dp
val CONTROLS_INFO_PILL_PADDING_VERTICAL = 8.dp
val CONTROLS_INFO_PILL_CORNER_RADIUS = 8.dp
val SKIP_ICON_SIZE = 32.dp
val PLAY_BUTTON_SIZE = 64.dp
val PLAY_ICON_SIZE = 36.dp
val CONTROLS_RESERVED_HEIGHT = 424.dp
val CONTROLS_COMPACT_RESERVED_HEIGHT = 244.dp

val ORP_HORIZONTAL_PADDING = 8.dp
val ORP_BASE_EDGE = 24.dp
val ORP_EXTRA_EDGE = 14.dp
val ORP_LINE_HEIGHT = 1.dp
val ORP_POINTER_HEIGHT = 12.dp
val ORP_POINTER_WIDTH = 1.dp
val ORP_TEXT_SPACER = 4.dp
val ORP_OPENING_PUNCTUATION = PAIRED_OPENING_PUNCTUATION_CHARS
