package com.example.kairo.ui.rsvp

import androidx.compose.ui.unit.dp
import com.example.kairo.core.model.RsvpFontFamily
import com.example.kairo.core.model.RsvpFontWeight

const val DEFAULT_FONT_SIZE_SP = 44f
val DEFAULT_FONT_FAMILY = RsvpFontFamily.INTER
val DEFAULT_FONT_WEIGHT = RsvpFontWeight.LIGHT
const val DEFAULT_TEXT_BRIGHTNESS = 0.88f
const val DEFAULT_VERTICAL_BIAS = -0.15f
const val DEFAULT_HORIZONTAL_BIAS = 0f

const val SAFE_MIN_TEMPO_MS_PER_WORD = 30L
const val EXTREME_MIN_TEMPO_MS_PER_WORD = 10L
const val MAX_TEMPO_MS_PER_WORD = 240L
const val DEFAULT_TEMPO_SCALE = 1.0
const val TEMPO_SCALE_MIN = 0.1
const val TEMPO_SCALE_MAX = 4.0
const val MIN_FRAME_DELAY_MS = 16L
const val POSITION_SAVE_INTERVAL_MS = 750L
const val TEMPO_STEP_MS = 5L
const val TEMPO_SWIPE_THRESHOLD_PX = 30f
const val POSITIONING_BIAS_PER_PX = 0.0015f

const val LOADING_TEXT_ALPHA = 0.6f
const val PROGRESS_PRIMARY_ALPHA = 0.7f
const val PROGRESS_TRACK_ALPHA = 0.3f
const val TOP_BAR_ICON_ALPHA = 0.3f
const val INDICATOR_BACKGROUND_ALPHA = 0.9f
const val QUICK_SETTINGS_BACKGROUND_ALPHA = 0.95f
const val POSITIONING_LINE_ALPHA = 0.18f
const val PROGRESS_TEXT_ALPHA = 0.6f
const val RESUME_TEXT_ALPHA = 0.4f

const val TEXT_BRIGHTNESS_MIN = 0.55f
const val TEXT_BRIGHTNESS_MAX = 1.0f
const val PIVOT_LINE_ALPHA_BASE = 0.15f
const val PIVOT_LINE_ALPHA_MIN = 0f
const val PIVOT_LINE_ALPHA_MAX = 1f

const val VERTICAL_BIAS_MIN = -0.7f
const val VERTICAL_BIAS_MAX = 0.7f
const val HORIZONTAL_BIAS_MIN = -0.6f
const val HORIZONTAL_BIAS_MAX = 0.6f

const val MIN_FONT_SIZE_SP = 28f
const val MAX_FONT_SIZE_SP = 80f

const val CONTROLS_HIDE_DELAY_MS = 3000L
const val TEMPO_INDICATOR_HIDE_DELAY_MS = 1500L
const val FONT_SIZE_INDICATOR_HIDE_DELAY_MS = 1500L

const val MS_PER_MINUTE = 60_000.0
const val MIN_WORD_COUNT = 1
const val MIN_TOTAL_MS = 1L

const val DEFAULT_PIVOT_INDEX = 0
const val INVALID_INDEX = -1
const val ORP_LOCK_PIVOT_WORDS = 1
const val ORP_LETTER_SPACING_SP = 0.5f
const val ORP_BIAS_FRACTION_MIN = 0.05f
const val ORP_BIAS_FRACTION_MAX = 0.95f
const val ORP_EDGE_FRACTION_MIN = 0.05f
const val ORP_EDGE_FRACTION_MAX = 0.45f
const val ORP_CENTER_FRACTION = 0.5f
const val ORP_TRANSFORM_ORIGIN_X = 0f
const val ORP_TRANSFORM_ORIGIN_Y = 0.5f
const val MIN_ORP_WIDTH_PX = 1f
const val ORP_MIN_AUTO_FIT_SCALE = 0.72f
const val ORP_ELLIPSIS = '\u2026'

const val ZERO_FLOAT = 0f
const val ONE_FLOAT = 1f
const val CENTER_BIAS = 0f
const val BIAS_SCALE_FACTOR = 2f

val PROGRESS_HEIGHT = 3.dp
val TOP_BAR_PADDING = 16.dp
val TOP_BAR_SPACING = 8.dp
val TOP_BAR_ICON_SIZE = 24.dp
val TEMPO_INDICATOR_TOP_PADDING = 60.dp
val FONT_SIZE_INDICATOR_TOP_PADDING = 112.dp
val INDICATOR_CORNER_RADIUS = 8.dp
val INDICATOR_PADDING_HORIZONTAL = 16.dp
val INDICATOR_PADDING_VERTICAL = 8.dp
val POSITIONING_INDICATOR_PADDING_HORIZONTAL = 14.dp
val POSITIONING_INDICATOR_PADDING_VERTICAL = 8.dp
val QUICK_SETTINGS_CORNER = 16.dp
val QUICK_SETTINGS_HORIZONTAL_PADDING = 16.dp
val QUICK_SETTINGS_VERTICAL_PADDING = 14.dp
val QUICK_SETTINGS_SPACING = 12.dp
const val QUICK_SETTINGS_HEIGHT_FRACTION = 0.85f
val POSITION_GUIDE_HEIGHT = 1.dp

val CONTROLS_PADDING = 24.dp
val CONTROLS_SPACER = 16.dp
val CONTROLS_HINT_SPACER = 8.dp
val CONTROLS_ROW_SPACING = 32.dp
val SKIP_ICON_SIZE = 32.dp
val PLAY_BUTTON_SIZE = 64.dp
val PLAY_ICON_SIZE = 36.dp

val ORP_HORIZONTAL_PADDING = 8.dp
val ORP_BASE_EDGE = 24.dp
val ORP_EXTRA_EDGE = 14.dp
val ORP_LINE_HEIGHT = 2.dp
val ORP_POINTER_HEIGHT = 12.dp
val ORP_POINTER_WIDTH = 2.dp
val ORP_TEXT_SPACER = 4.dp

val ORP_OPENING_PUNCTUATION = setOf('(', '[', '{', '\u201C', '\u2018')
