package com.kairo.reader.core.model

/** Reading styles share safety floors; each profile changes cadence rather than display preferences. */
fun RsvpProfile.defaultConfig(): RsvpConfig = when (this) {
    RsvpProfile.BALANCED -> naturalReadingDefaults()
    RsvpProfile.CHILL -> chillReadingDefaults()
    RsvpProfile.NARRATIVE -> narrativeReadingDefaults()
    RsvpProfile.FOCUS -> focusReadingDefaults()
    RsvpProfile.FLOW -> flowReadingDefaults()
    RsvpProfile.SPRINT -> skimReadingDefaults()
    RsvpProfile.STUDY -> studyReadingDefaults()
}

private fun naturalReadingDefaults() = RsvpConfig(
    tempoMsPerWord = 155L,
    minWordMs = 55L,
    longWordMinMs = 160L,
    longWordChars = 12,
    maxChunkLength = 24,
    syllableExtraMs = 14L,
    rarityExtraMaxMs = 55L,
    complexityStrength = 0.55,
    lengthStrength = 0.85,
    lengthExponent = 1.30,
    enablePhraseChunking = true,
    maxWordsPerUnit = 2,
    maxCharsPerUnit = 14,
    subwordChunkPauseMs = 45L,
    commaPauseMs = 190L,
    periodPauseMs = 380L,
    semicolonPauseMs = 330L,
    colonPauseMs = 300L,
    dashPauseMs = 290L,
    parenthesesPauseMs = 150L,
    quotePauseMs = 80L,
    sentenceEndPauseMs = 410L,
    paragraphPauseMs = 450L,
    paragraphPauseMultiplier = 1.35,
    pageBreakPauseMultiplier = 3.20,
    pauseScaleExponent = 0.44,
    minPauseScale = 0.84,
    punctuationPauseFactor = 1.0,
    parentheticalMultiplier = 1.08,
    dialogueMultiplier = 1.0,
    dialoguePunctuationScale = 1.0,
    smoothingAlpha = 0.30,
    maxSpeedupFactor = 1.18,
    maxSlowdownFactor = 1.38,
    startDelayMs = 240L,
    endDelayMs = 300L,
    rampUpFrames = 4,
    rampDownFrames = 3,
    adaptiveDifficultyMaxHoldMs = 60L,
    complexWordHoldMs = 40L,
    clausePauseFactor = 1.20,
    prosodyStrength = 0.80,
    focalSupportCompression = 0.96,
    anticipatoryLandingBoost = 1.04,
    parentheticalAsideMultiplier = 0.95,
)

/** Space between thoughts, with restrained movement inside each phrase. */
private fun chillReadingDefaults() = naturalReadingDefaults().copy(
    tempoMsPerWord = 215L,
    minWordMs = 70L,
    longWordMinMs = 200L,
    rarityExtraMaxMs = 50L,
    complexityStrength = 0.50,
    lengthStrength = 0.80,
    smoothingAlpha = 0.18,
    maxSpeedupFactor = 1.12,
    maxSlowdownFactor = 1.28,
    commaPauseMs = 205L,
    semicolonPauseMs = 380L,
    colonPauseMs = 350L,
    dashPauseMs = 335L,
    periodPauseMs = 460L,
    sentenceEndPauseMs = 495L,
    paragraphPauseMs = 650L,
    paragraphPauseMultiplier = 1.50,
    pageBreakPauseMultiplier = 3.30,
    prosodyStrength = 0.50,
    focalSupportCompression = 0.98,
    anticipatoryLandingBoost = 1.03,
    startDelayMs = 400L,
    rampUpFrames = 6,
    endDelayMs = 400L,
)

/** A gentle spoken contour, without routinely rushing quoted speech. */
private fun narrativeReadingDefaults() = naturalReadingDefaults().copy(
    minWordMs = 60L,
    longWordMinMs = 170L,
    maxCharsPerUnit = 18,
    prosodyStrength = 1.15,
    dialogueMultiplier = 0.98,
    quotePauseMs = 130L,
    semicolonPauseMs = 340L,
    dashPauseMs = 320L,
    periodPauseMs = 420L,
    sentenceEndPauseMs = 450L,
    paragraphPauseMs = 560L,
    paragraphPauseMultiplier = 1.45,
    pageBreakPauseMultiplier = 3.50,
    focalSupportCompression = 0.94,
    anticipatoryLandingBoost = 1.07,
    smoothingAlpha = 0.32,
    maxSpeedupFactor = 1.20,
    maxSlowdownFactor = 1.45,
)

/** Predictable single-word presentation with safety and punctuation still intact. */
private fun focusReadingDefaults() = naturalReadingDefaults().copy(
    minWordMs = 65L,
    longWordMinMs = 165L,
    enablePhraseChunking = false,
    smoothingAlpha = 0.16,
    maxSpeedupFactor = 1.10,
    maxSlowdownFactor = 1.22,
    useProsodyPacing = false,
    prosodyStrength = 0.0,
    useFocalStress = false,
    focalSupportCompression = 1.0,
    useAnticipatoryLanding = false,
    anticipatoryLandingBoost = 1.0,
    useDialogueDetection = false,
    rarityExtraMaxMs = 50L,
    commaPauseMs = 155L,
    periodPauseMs = 345L,
    sentenceEndPauseMs = 370L,
    paragraphPauseMs = 430L,
)

/** Longer coherent units, with light transitions between them. */
private fun flowReadingDefaults() = naturalReadingDefaults().copy(
    longWordMinMs = 150L,
    maxWordsPerUnit = 3,
    maxCharsPerUnit = 22,
    smoothingAlpha = 0.35,
    maxSpeedupFactor = 1.20,
    maxSlowdownFactor = 1.34,
    prosodyStrength = 0.65,
    focalSupportCompression = 0.97,
    anticipatoryLandingBoost = 1.03,
    commaPauseMs = 160L,
    periodPauseMs = 345L,
    sentenceEndPauseMs = 375L,
    paragraphPauseMs = 430L,
    paragraphPauseMultiplier = 1.30,
    rarityExtraMaxMs = 50L,
    complexityStrength = 0.50,
    lengthStrength = 0.80,
)

/** Efficient review: reduce ornament, never omit source words or punctuation floors. */
private fun skimReadingDefaults() = naturalReadingDefaults().copy(
    tempoMsPerWord = 125L,
    longWordMinMs = 150L,
    maxCharsPerUnit = 16,
    syllableExtraMs = 10L,
    rarityExtraMaxMs = 30L,
    complexityStrength = 0.35,
    lengthStrength = 0.65,
    lengthExponent = 1.20,
    adaptiveDifficultyMaxHoldMs = 25L,
    complexWordHoldMs = 20L,
    complexWordThreshold = 1.50,
    useProsodyPacing = false,
    prosodyStrength = 0.0,
    useFocalStress = false,
    focalSupportCompression = 1.0,
    useAnticipatoryLanding = false,
    anticipatoryLandingBoost = 1.0,
    useDialogueDetection = false,
    commaPauseMs = 125L,
    semicolonPauseMs = 255L,
    colonPauseMs = 235L,
    dashPauseMs = 225L,
    parenthesesPauseMs = 110L,
    quotePauseMs = 65L,
    periodPauseMs = 290L,
    sentenceEndPauseMs = 315L,
    paragraphPauseMs = 360L,
    paragraphPauseMultiplier = 1.20,
    pageBreakPauseMultiplier = 3.0,
    minPauseScale = 0.82,
    startDelayMs = 200L,
    rampUpFrames = 3,
    endDelayMs = 250L,
)

/** Protect unfamiliar terms and completed ideas, without expressive compression. */
private fun studyReadingDefaults() = naturalReadingDefaults().copy(
    tempoMsPerWord = 185L,
    minWordMs = 80L,
    longWordMinMs = 240L,
    longWordChars = 10,
    maxChunkLength = 32,
    enablePhraseChunking = false,
    maxCharsPerUnit = 16,
    syllableExtraMs = 22L,
    rarityExtraMaxMs = 100L,
    complexityStrength = 0.95,
    lengthStrength = 1.05,
    lengthExponent = 1.35,
    adaptiveDifficultyMaxHoldMs = 100L,
    complexWordHoldMs = 65L,
    complexWordThreshold = 1.20,
    prosodyStrength = 0.60,
    useFocalStress = false,
    focalSupportCompression = 1.0,
    useAnticipatoryLanding = false,
    anticipatoryLandingBoost = 1.0,
    useDialogueDetection = false,
    smoothingAlpha = 0.30,
    maxSpeedupFactor = 1.10,
    maxSlowdownFactor = 1.75,
    commaPauseMs = 205L,
    semicolonPauseMs = 420L,
    colonPauseMs = 440L,
    dashPauseMs = 370L,
    periodPauseMs = 505L,
    sentenceEndPauseMs = 550L,
    paragraphPauseMs = 680L,
    paragraphPauseMultiplier = 1.45,
    pageBreakPauseMultiplier = 3.50,
    startDelayMs = 350L,
    rampUpFrames = 6,
    endDelayMs = 450L,
)

/** Speed and visual aids belong to the reader, independently of the selected cadence. */
fun RsvpConfig.withReaderPreferencesFrom(current: RsvpConfig): RsvpConfig =
    copy(
        tempoMsPerWord = current.tempoMsPerWord,
        baseWpm = current.baseWpm,
        contextAssistMode = current.contextAssistMode,
        blinkMode = current.blinkMode,
        orpEnabled = current.orpEnabled,
        orpHighlightEnabled = current.orpHighlightEnabled,
        orpGuideEnabled = current.orpGuideEnabled,
        orpGuideBrightness = current.orpGuideBrightness,
        orpGuideThickness = current.orpGuideThickness,
    )

/** Compare only the settings a reading preset owns. */
fun RsvpConfig.profileCadenceIdentity(): RsvpConfig = withReaderPreferencesFrom(RsvpConfig())
